### ISSUE TITLE
AD deployment fails

### ISSUE THREAD

**Issue by hjorrip** [DefensiveOrigins/DO-LAB#4]
Windows server version incorrect. 
Also had an issue when I updated the Windows server version in the forked template, it failed installing sysmon.

**Comment by hjorrip** [comment]
{
  "code": "DeploymentFailed",
  "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.",
  "details": [
    {
      "code": "VMExtensionProvisioningError",
      "message": "VM has reported a failure when processing extension 'PowerShellDSC' (publisher 'Microsoft.Powershell' and type 'DSC'). Error message: \"DSC Configuration 'Install-Sysmon' completed with error(s). Following are the first few: PowerShell DSC resource DSC_xScriptResource  failed to execute Set-TargetResource functionality with error message: System.InvalidOperationException: The set script threw an error. ---> Microsoft.PowerShell.Commands.ServiceCommandException: Service 'Sysmon (sysmon)' cannot be stopped due to the following error: Cannot stop sysmon service on computer '.'. ---> System.InvalidOperationException: Cannot stop sysmon service on computer '.'. ---> System.ComponentModel.Win32Exception: Access is denied\r\n   --- End of inner exception stack trace ---\r\n   at System.ServiceProcess.ServiceController.Stop()\r\n   at Microsoft.PowerShell.Commands.ServiceOperationBaseCommand.DoStopService(ServiceController serviceController, Boolean force, Boolean waitForServiceToStop)\r\n   --- End of inner exception stack trace ---\r\n   --- End of inner exception stack trace ---  The SendConfigurationApply function did not succeed.\". More information on troubleshooting is available at https://aka.ms/VMExtensionDSCWindowsTroubleshoot. "
    }
  ]
}

**Comment by cybersader** [comment]
I've had the same issues trying to use this deployment

**Comment by hjorrip** [comment]
@cybersader - I've figured out that this project inherited an issue from it's forked/original project, Sentinel2Go.

**Comment by cybersader** [comment]
@hjorrip You have a solution? 😁.  I wanted to deploy this so I could try some password spray and fake user account stuff, but I'm definitely not familiar with Azure Resource Manager or Azure in general

**Comment by cybersader** [comment]
I might've fixed it in my fork - https://github.com/cybersader/DO-LAB/tree/main

**Comment by hjorrip** [comment]
@cybersader I made a fix for the windows server version issue here on my fork:
https://github.com/hjorrip/DO-LAB/tree/patch-1

However, the Sysmon issue is rooted in the Sentinel2Go project which I did not debug, and I'm afraid that using this project, you're gonna need that if you want to look at the artifacts in Sentinel. 

If you want to play around with "on-prem" virtual machines, domain joined and all that - you could just sign up for Defender for Endpoint trial:
https://www.microsoft.com/en-us/security/business/endpoint-security/microsoft-defender-endpoint

Once you have that, you can login to security.microsoft.com using the provided credentials, and use their "Evaluation lab":
https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/evaluation-lab?view=o365-worldwide

It's a very underrated feature - you can create a DC, and bunch of domain joined devices (for free! - but limited time), as well as a Linux attack machine. One addede benefit from this is the devices you create using the Evaluation lab, will be onboarded to Defender for Endpoint. So all hunting you want to do, can then be done using the Device Logs in Advanced Hunting in the security portal. 

It's a different take, but if you want to try out password spraying - this could be pretty cool. If you want to take it even a step further, you could sign up for Defender for Identity trial and install the sensor on the domain controller  see how that reacts when you spray - but installing the sensor is quite hands on and I'm not aware of a "plug-n-play solution for that".

**Comment by Relkci** [comment]
we apologize for missing this earlier.  We're working on a new builder for our rebuild of APT class that we will be releasing next year.  There have been a handful of changes to both ARM templates and the various tooling that DO-LAB builds out-- despite alot of effort was put into building these, we've decided to build a new set again.  When completed, we will fully deprecate this repo and point to the new one so as to not have anyone put too much effort into trying to keep this template updated since we are rebuilding in a new repo.

In the mean time, we'd recommend https://github.com/OTRF/Microsoft-Sentinel2Go  for generic Sentinel buildouts.  

Even the new ARM template we are building will be a custom variation of a Sentinel2Go build.

Cheers!

**Comment by cybersader** [comment]
@Relkci I was trying to recreate the password spray and cyber deception techniques with some modifications for a grad school class.  I'm going to move forward with attempting to fix issues with the Install-Sysmon.ps1 command since I have to have it done by December, but thanks for the reply! 😊 I'm also still familiarizing myself with Azure, so I may have to outsource the debugging.

Ironically, I bet I'll take that class once it arrives 😆

**Comment by Relkci** [comment]
yeah, I was mistaken, we're working on fixing it right now :)

**Comment by Relkci** [comment]
SKUs and versions have been updated, VMSizes moved to require hypervisor gen2; sysmon install has been updated.   New deployments appear to be working without errors.  Please let us know if new issues arise
